---
ID: "b22b39c2-c51d-448e-af5c-45174aacd622"
Parent: "24f5614b-e302-4f6d-9149-995c84d28e46"
Template: "24f5614b-e302-4f6d-9149-995c84d28e46"
Path: /sitecore/templates/Project/retail/Page_2/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {98E60957-0783-4A9A-85CC-77DAD30E9711}
    {C14B6289-8AC2-439C-9E5B-40DE9F820C3F}
    {412BF445-B1A6-4AFF-8054-0B21A1FEBC47}
    {F6E44A9E-074A-4865-987E-0C2DC00B7AF5}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "772028fc-d341-4d11-bb3f-55aaa66cdb23"
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250820T091612Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "6f408edf-db0b-4256-ab71-0b0ce47c4f28"
      Hint: Title
      Value: $name
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5139c89d-a3ee-4688-a462-497abb73691c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ranula.gamage@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20250924T123210Z
